<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>KnighterAndroid</AssemblyName>
    <LangVersion>latest</LangVersion>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <NoWarn>CS0169;CS0219;CS0414;CS0649;CS1717</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="../base/assemblies/*.dll"
               Exclude="../base/assemblies/KnighterAndroid.dll;
                        ../base/assemblies/mscorlib.dll;
                        ../base/assemblies/System.dll;
                        ../base/assemblies/System.Core.dll;
                        ../base/assemblies/System.Xml.dll;
                        ../base/assemblies/System.Xml.Linq.dll;
                        ../base/assemblies/System.Runtime.Serialization.dll;
                        ../base/assemblies/Microsoft.CSharp.dll;
                        ../base/assemblies/Mono.Security.dll;
                        ../base/assemblies/I18N*.dll" />
  </ItemGroup>

</Project>